default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ag11_development

test:
  <<: *default
  database: ag11_test

production:
  <<: *default
  database: cryptonaza_production
  username: cryptonaza
  password: <%= ENV['AG11_DATABASE_PASSWORD'] %>
